apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  {{- template "mychart.labels"}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
        - name: nginx
          image: nginx:1.27
          ports:
            - containerPort: 80